#!/bin/bash
RES=$( cd "$(dirname "$0")" ; pwd -P )/res
PATH=$RES:$PATH
mkdir $RES/wallets
mkdir $RES/data
ginkou-loader --html-path $RES/ginkou-public --wallet-dir $RES/wallets --data-path $RES/data 

