name: Test-Build-Release

on:
  push: 
    # branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    needs: build-mac
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - run: ls
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submodule Clone
        run: git submodule update --init --recursive
      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: ginkou.flatpak
          manifest-path: flatpak/org.themelio.Wallet.yml
          cache-key: flatpak-builder-${{  hashFiles('**/flatpak/org.themelio.Wallet.yml') }}

      - name: Upload flatpak artifact
        uses: actions/upload-artifact@v2
        with:
          name: ginkou.flatpak
          path: ginkou-x86_64


  build-ginkou:
    runs-on: macos-latest
    steps: 

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Submodule Clone
        run: git submodule update --init --recursive
      
      - uses: actions/cache@v2
        id: ginkou-cache
        with:
          path: |
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/mac/artifacts/ginkou-public
          key: ${{ runner.os }}-npm-${{ hashFiles('**/ginkou/yarn.lock') }}-debug

      - name: install ginkou
        if: steps.ginkou-cache.outputs.cache-hit != 'true'
        run: ./mac/build-mac.sh --ginkou


      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: ginkou-public
      #     path: mac/artifacts/ginkou-public/
    
  mac-ginkou-loader:
      
    runs-on: macos-latest
    name: Build Macos Ginkou-loader
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Submodule Clone
        run: git submodule update --init --recursive

      - uses: actions/cache@v2
        id: ginkou-loader-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/mac/artifacts/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/ginkou-loader/Cargo.lock') }}-debug
        
      - name: Install rust toolchain
        if: steps.ginkou-loader-cache.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        
      - name: install ginkou-loader
        if: steps.ginkou-loader-cache.outputs.cache-hit != 'true'
        run: ./mac/build-mac.sh --ginkou-loader 
      - uses: actions/upload-artifact@v2
        with:
          name: ginkou-loader
          path: mac/artifacts/ginkou-loader  
 
  mac-melwalletd:    
    runs-on: macos-latest
    name: Build Macos melwalletd

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Submodule Clone
        run: git submodule update --init --recursive
      
      - uses: actions/cache@v2
        id: melwalletd-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/mac/artifacts/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/melwalletd/Cargo.lock') }}-debug
      
      - name: Install rust toolchain
        if: steps.melwalletd-cache.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        
      - name: install melwalletd
        if: steps.melwalletd-cache.outputs.cache-hit != 'true'
        run: ./mac/build-mac.sh --melwalletd 
      
      - uses: actions/upload-artifact@v2
        with:
          name: melwalletd
          path: mac/artifacts/melwalletd

  build-mac:
    name: Build MacOS App 
    needs: [mac-ginkou-loader, build-ginkou, mac-melwalletd]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Submodule Clone
        run: git submodule update --init --recursive

      - uses: actions/cache@v2
        id: cache
        with:
          path: 
            /usr/local/bin/create-dmg
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/mac/ginkou.dmg
          key: ${{ runner.os }}-ginkou.app-${{ hashFiles('**/mac') }}-debug-cache-miss
           
      - name: Install create-dmg
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install create-dmg

     # download all artifacts
     # this will work until other artifacts are added
      - uses: actions/download-artifact@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: mac/artifacts/
      - run: ls
      - if: steps.cache.outputs.cache-hit != 'true'
        run: ./mac/build-mac.sh --app --dmg
      - run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: ginkou.append
          path: mac/ginkou.dmg



  release:
      needs: [build-ubuntu, build-mac]
      runs-on: ubuntu-latest
         
      steps:
        - name: Delete drafts
          uses: hugo19941994/delete-draft-releases@v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: actions/download-artifact@v2
          with:
            # not sure how this is created?
            # have faith in the flatpak-github-actions gods
            name: ginkou.flatpak

        - name: Release
          uses: softprops/action-gh-release@v1
          # if: startsWith(github.ref, 'refs/tags/')
          with:
            body: this is a test
            # files: |
            #   ginkou-x86_64 


# This is a basic workflow to help you get started with Actions


