name: Test-Build-Release

on:
  push:
  # pull_request:
  #   branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submodule Clone
        run: git submodule update --init --recursive
      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: ginkou.flatpak
          manifest-path: flatpak/org.themelio.Wallet.yml
          cache-key: flatpak-builder-testing
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ginkou.flatpak
            ginkou_app

# This is a basic workflow to help you get started with Actions


