name: Build

#on:
#  pull_request:
#    branches: [ master ]

on:
  push:
    branches: [ meade-ci ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt -y install flatpak flatpak-builder libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Add Flathub Repository
        run: sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install Flatpak Dependencies
        run: sudo flatpak install -y flathub org.gnome.Sdk/x86_64/40 org.gnome.Platform/x86_64/40 org.freedesktop.Sdk.Extension.rust-stable//20.08 org.freedesktop.Sdk.Extension.node14//20.08

      - name: Build
        run: flatpak-builder build org.themelio.Wallet.yml --force-clean --user