name: Test-Build-Release

on:
  push: 
    # branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    needs: build-mac
    runs-on: ubuntu-latest

    # container:
    #   image: bilelmoussaoui/flatpak-github-actions:gnome-40
    #   options: --privileged
    steps:
      - run: ls
    #   - name: Checkout
    #     uses: actions/checkout@v2
      # - name: Submodule Clone
      #   run: git submodule update --init --recursive
      # - name: Build
      #   uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      #   with:
      #     bundle: ginkou.flatpak
      #     manifest-path: flatpak/org.themelio.Wallet.yml
      #     cache-key: flatpak-builder-${{ github.sha }}
      # - run: echo "0 bytes" > ginkou-x86_64
      # - name: Upload flatpak artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ginkou.flatpak
      #     path: ginkou-x86_64
  build-mac:
    name: Build MacOS App 
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Submodule Clone
        run: git submodule update --init --recursive
      # - name: Install create-dmg
      #   run: test && brew install create-dmg
      # - uses: Swatinem/rust-cache@v1
      #   with: 
      #     target-dir: ginkou-loader/target
      - run: pwd
      - run: ls -la ~/
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/ginkou-loader/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-debug
      # - uses: actions/cache@v2
      #   with:
      #     path: melwalletd/target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('melwalletd/Cargo.lock') }}
      # - uses: actions/cache@v2
      #   with:
      #     path: ginkou-loader/target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('ginkou-loader/Cargo.lock') }}
      # - run: cargo install --locked --path $PROJECT_ROOT/ginkou-loader/ --root $RES/tmp
      - run: ./mac/build-mac.sh
      - run: ls -la ginkou-loader
      - run: ls -la ginkou-loader/target/*



  # release:
  #     needs: [build-ubuntu, build-mac]
  #     runs-on: ubuntu-latest
         
  #     steps:
  #       - name: Delete drafts
  #         uses: hugo19941994/delete-draft-releases@v1.0.0
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       # - uses: actions/download-artifact@v2
  #       #   with:
  #       #     # not sure how this is created?
  #       #     # have faith in the flatpak-github-actions gods
  #       #     name: ginkou.flatpak
       
  #       - name: Release
  #         uses: softprops/action-gh-release@v1
  #         # if: startsWith(github.ref, 'refs/tags/')
  #         with:
  #           body: this is a test
  #           # files: |
  #           #   ginkou-x86_64 


# This is a basic workflow to help you get started with Actions


