name: Test-Build-Release

on:
  push: 
    # branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build-ubuntu:
  #   needs: build-mac
  #   runs-on: ubuntu-latest

  #   # container:
  #   #   image: bilelmoussaoui/flatpak-github-actions:gnome-40
  #   #   options: --privileged
  #   steps:
  #     - run: ls
  #   #   - name: Checkout
  #   #     uses: actions/checkout@v2
  #     # - name: Submodule Clone
  #     #   run: git submodule update --init --recursive
  #     # - name: Build
  #     #   uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
  #     #   with:
  #     #     bundle: ginkou.flatpak
  #     #     manifest-path: flatpak/org.themelio.Wallet.yml
  #     #     cache-key: flatpak-builder-${{ github.sha }}
  #     # - run: echo "0 bytes" > ginkou-x86_64
  #     # - name: Upload flatpak artifact
  #     #   uses: actions/upload-artifact@v2
  #     #   with:
  #     #     name: ginkou.flatpak
  #     #     path: ginkou-x86_64
  # build-ginkou-artifacts: 
  #   name: build Ginkou Wallet
  #   runs-on: ubuntu-latest
  #   steps:

  #     - uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           ginkou-loader/target
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/ginkou-loader/Cargo.lock') }}-debug

  cache-mac-app:
    
    runs-on: ubuntu-latest
    name: Cache ginkou.app
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Submodule Clone
        run: git submodule update --init --recursive
      
      - uses: actions/cache@v2
        id: ginkou-cache
        with:
          path: |
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/mac/artifacts/ginkou-public
          key: ${{ runner.os }}-npm-${{ hashFiles('**/ginkou/yarn.lock') }}-debug
        
      - run: mkdir -p mac/artifacts
      - run: ls mac/artifacts
        
      - uses: actions/cache@v2
        id: ginkou-loader-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/artifacts/ginkou-loader
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/ginkou-loader/Cargo.lock') }}-debug
      
      - run: ls mac/artifacts

      - uses: actions/cache@v2
        id: melwalletd-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/artifacts/melwalletd
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/melwalletd/Cargo.lock') }}-debug
      - run: ls mac/artifacts
      - name: Install rust toolchain
        if: steps.ginkou-cache.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        
      - name: install ginkou
        if: steps.ginkou-cache.outputs.cache-hit != 'true'
        run: ./mac/build-mac.sh --ginkou 

      - name: install ginkou-loader
        if: steps.ginkou-loader-cache.outputs.cache-hit != 'true'
        run: ./mac/build-mac.sh --ginkou-loader 

      - name: install melwalletd
        if: steps.melwalletd-cache.outputs.cache-hit != 'true'
        run: ./mac/build-mac.sh --melwalletd 

  # build-mac:
  #   name: Build MacOS App 
  #   runs-on: macos-latest
  #   needs: build-rust-artifacts
  #   steps:
     
  #     # - name: Install create-dmg
  #     #   run: test && brew install create-dmg

  #     - run: pwd
  #     - run: ls -la ~/
  #     - uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           /Users/runner/work/ginkou-flatpak/ginkou-flatpak/ginkou-loader/target
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/ginkou-loader/Cargo.lock') }}-debug
  #     # - uses: actions/cache@v2
  #     #   with:
  #     #     path: melwalletd/target/
  #     #     key: ${{ runner.os }}-cargo-${{ hashFiles('melwalletd/Cargo.lock') }}
  #     # - uses: actions/cache@v2
  #     #   with:
  #     #     path: ginkou-loader/target/
  #     #     key: ${{ runner.os }}-cargo-${{ hashFiles('ginkou-loader/Cargo.lock') }}
  #     # - run: cargo install --locked --path $PROJECT_ROOT/ginkou-loader/ --root $RES/tmp
  #     - run: ls -lah ginkou-loader/target/*
  #     - run: ./mac/build-mac.sh
  #     - run: ls -lah ginkou-loader/target/*
  #     - run: ls -la ginkou-loader



  # release:
  #     needs: [build-ubuntu, build-mac]
  #     runs-on: ubuntu-latest
         
  #     steps:
  #       - name: Delete drafts
  #         uses: hugo19941994/delete-draft-releases@v1.0.0
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       # - uses: actions/download-artifact@v2
  #       #   with:
  #       #     # not sure how this is created?
  #       #     # have faith in the flatpak-github-actions gods
  #       #     name: ginkou.flatpak
       
  #       - name: Release
  #         uses: softprops/action-gh-release@v1
  #         # if: startsWith(github.ref, 'refs/tags/')
  #         with:
  #           body: this is a test
  #           # files: |
  #           #   ginkou-x86_64 


# This is a basic workflow to help you get started with Actions


