name: Test-Build-Release

on:
  push: 
    # branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build-ubuntu:
  #   needs: build-mac
  #   runs-on: ubuntu-latest

  #   # container:
  #   #   image: bilelmoussaoui/flatpak-github-actions:gnome-40
  #   #   options: --privileged
  #   steps:
  #     - run: ls
  #   #   - name: Checkout
  #   #     uses: actions/checkout@v2
  #     # - name: Submodule Clone
  #     #   run: git submodule update --init --recursive
  #     # - name: Build
  #     #   uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
  #     #   with:
  #     #     bundle: ginkou.flatpak
  #     #     manifest-path: flatpak/org.themelio.Wallet.yml
  #     #     cache-key: flatpak-builder-${{ github.sha }}
  #     # - run: echo "0 bytes" > ginkou-x86_64
  #     # - name: Upload flatpak artifact
  #     #   uses: actions/upload-artifact@v2
  #     #   with:
  #     #     name: ginkou.flatpak
  #     #     path: ginkou-x86_64

  build-rust-artifacts:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}, rust, build, cache

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Submodule Clone
        run: git submodule update --init --recursive
      - run: pwd
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ginkou-loader/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/ginkou-loader/Cargo.lock') }}-debug
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd ginkou-loader
      - uses: actions-rs/cargo@v1
        with:
          command: build
  build-mac:
    name: Build MacOS App 
    runs-on: macos-latest
    steps:
     
      # - name: Install create-dmg
      #   run: test && brew install create-dmg

      - run: pwd
      - run: ls -la ~/
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            /Users/runner/work/ginkou-flatpak/ginkou-flatpak/ginkou-loader/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/ginkou-loader/Cargo.lock') }}-debug
      # - uses: actions/cache@v2
      #   with:
      #     path: melwalletd/target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('melwalletd/Cargo.lock') }}
      # - uses: actions/cache@v2
      #   with:
      #     path: ginkou-loader/target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('ginkou-loader/Cargo.lock') }}
      # - run: cargo install --locked --path $PROJECT_ROOT/ginkou-loader/ --root $RES/tmp
      - run: ls -lah ginkou-loader/target/*
      - run: ./mac/build-mac.sh
      - run: ls -lah ginkou-loader/target/*
      - run: ls -la ginkou-loader



  # release:
  #     needs: [build-ubuntu, build-mac]
  #     runs-on: ubuntu-latest
         
  #     steps:
  #       - name: Delete drafts
  #         uses: hugo19941994/delete-draft-releases@v1.0.0
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       # - uses: actions/download-artifact@v2
  #       #   with:
  #       #     # not sure how this is created?
  #       #     # have faith in the flatpak-github-actions gods
  #       #     name: ginkou.flatpak
       
  #       - name: Release
  #         uses: softprops/action-gh-release@v1
  #         # if: startsWith(github.ref, 'refs/tags/')
  #         with:
  #           body: this is a test
  #           # files: |
  #           #   ginkou-x86_64 


# This is a basic workflow to help you get started with Actions


